package com.example.android.takehomeassignment11_katieb;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ImageView;
import android.widget.TextView;

public class FindOutMore extends AppCompatActivity {

    private ImageView photo;
    private TextView name;
    private TextView info;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_find_out_more);

        photo = (ImageView) findViewById(R.id.more_photo);
        name = (TextView) findViewById(R.id.more_name);
        info = (TextView) findViewById(R.id.more_info);

        Intent intent = getIntent();
        CarbonAction c = (CarbonAction) intent.getSerializableExtra(Keys.CARBON);

        photo.setImageResource(c.getPhotoID());
        name.setText(c.getName());

        if (c.getName().equals("Ride a bike or take public transportation"))
            info.setText("Our personal vehicles are a major cause of global warming. " +
                    "Collectively, cars and trucks account for nearly one-fifth of all US " +
                    "emissions, emitting around 24 pounds of carbon dioxide and other " +
                    "global-warming gases for every gallon of gas.");
        else if (c.getName().equals("Switch to clean energy"))
            info.setText("Approximately 67% of electricity in the U.S. " +
                    "is generated by burning fossil fuels, according to U.S. Energy Information " +
                    "Administration. Reducing the electricity we draw from the grid " +
                    "means reducing carbon emissions—in fact, SEIA reports that solar energy has " +
                    "offset 37 million metric tons of CO2 emissions, equivalent to planting 956 million " +
                    "trees!");
        else if (c.getName().equals("Pass up fast fashion with secondhand goodness"))
            info.setText("Do you really want that shirt? Sure, it's only eight bucks from" +
                    " Forever 21, and you DO need something to wear out tonight, but where will it " +
                    "end up? 84% of unwanted clothing in the United States ends up in landfills. Thrift your" +
                    " new clothes for a completely unique look and recycle your old.");
        else if (c.getName().equals("Bring your own tote or mug"))
            info.setText("Plastic bags are mostly made out of polyethylene, " +
                    "which is a byproduct of petroleum and natural gas. As plastic bags decompose into little pieces, " +
                    "they release greenhouse gas emissions into the atmosphere, adding another number " +
                    "to the long list of anthropogenic climate change sources. Plastic bag production " +
                    "also increases dependence on foreign oil reserves. The lifecycle of a plastic bag " +
                    "begins with the extraction of crude oil or natural gas and goes all the way to the end of " +
                    "that century it can take for to decompose.");
        else
            info.setText("Raising animals for food requires " +
                    "massive amounts of land, food, energy, and water and causes immense animal " +
                    "suffering. A staggering 51 percent or more of global greenhouse-gas " +
                    "emissions are caused by animal agriculture, according to a report published " +
                    "by the Worldwatch Institute.");

    }
}


// Add nonspecific intent to work with phone's map function: find fancy vintage, find cheap thrifts,
// find solar company, find good vegan food, etc.